services:
  - type: web
    name: telegram-web-app
    env: go
    plan: free
    rootDir: server
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
    buildEnvironment:
      GO_VERSION: 1.25.3
